### ISSUE TITLE
android : java.lang.NumberFormatException error

### ISSUE THREAD

**Issue by asamaru7** [jhalterman/typetools#24]
in android project unittest :

Caused by: java.lang.NumberFormatException: For input string: "1.7.0_79"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:492)
	at java.lang.Integer.valueOf(Integer.java:582)
	at net.jodah.typetools.TypeResolver.<clinit>(TypeResolver.java:54)

**Comment by jhalterman** [comment]
@asamaru7 I just pushed a fix. Are you able to try it out to make sure things work well for you?
